name: "Protobuf Generation"

on:
  push:
    branches:
      - main
    paths:
        - 'proto/**/*.proto'
    tags:
        - 'v1.*.*'

jobs:
    protoc:
      name: Generate Protobuf
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: 'stable'
            check-latest: true

        - name: Install Protocol Buffer Compiler
          uses: arduino/setup-protoc@v3

        - name: Install Protocol Buffer Plugins
          run: |
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

        - name: Make the script executable
          run: chmod +x ./protoc-gen-go.sh
          
        - name: Generate Go code from protocol buffer definitions
          run: ./protoc-gen-go.sh

        - name: Commit and push changes
          run: |
            git config --global user.email "nuraddinov4101@gmail.com"
            git config --global user.name "lmnq"
            git add .
            git commit -m "Update generated code"
            git push